version: '3.5'

services:

  prometheus:
    build: .
    ports:
      - 9090:9090
    environment:
      - SCRAPE_INTERVAL=15s
      - SCRAPE_TIMEOUT=10s
      - STATIC_SCRAPE_TARGETS=scraphere11@scraphere1:8384 scraphere22@scrapehere2:38485
      - DNS_SCRAPE_TARGETS=dnsscrape11@dnsscrape1:1111 dnsscrape22@dnsscrape2:2222

  